name: flutter_egg
description: 像安卓彩蛋一样的隐藏功能,通过多次点击可触发彩蛋
version: 1.0.3
homepage: https://github.com/Tyrone2333/flutter_egg

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

